<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>Polyglossy.Interactive.PackageManagement</AssemblyName>
    <PackageId>Microsoft.DotNet.Interactive.PackageManagement</PackageId>
    <NoWarn>$(NoWarn);8002;CS8002</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageDescription>Core types for adding Nuget support when using interactive programming for .NET.</PackageDescription>
    <PackageTags>polyglot notebook dotnet interactive packagemanagement nuget</PackageTags>
    <RootNamespace>Microsoft.DotNet.Interactive.PackageManagement</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Compiler.Service" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.DotNet.Interactive\Microsoft.DotNet.Interactive.csproj" />
  </ItemGroup>

  <Target Name="CreateLegacyAssemblyFileName" AfterTargets="Build">
    <Copy SourceFiles="$(TargetDir)$(AssemblyName).dll"
          DestinationFiles="$(TargetDir)Microsoft.DotNet.Interactive.PackageManagement.dll"
          SkipUnchangedFiles="true"
          Condition="Exists('$(TargetDir)$(AssemblyName).dll') and '$(AssemblyName)' != 'Microsoft.DotNet.Interactive.PackageManagement'" />
    <Copy SourceFiles="$(TargetDir)$(AssemblyName).pdb"
          DestinationFiles="$(TargetDir)Microsoft.DotNet.Interactive.PackageManagement.pdb"
          SkipUnchangedFiles="true"
          Condition="Exists('$(TargetDir)$(AssemblyName).pdb') and '$(AssemblyName)' != 'Microsoft.DotNet.Interactive.PackageManagement'" />
  </Target>
</Project>
